package com.matmuh.matmuhsite.entities.cms;

import com.fasterxml.jackson.annotation.JsonValue;

public enum SlugSource {

    AUTO_GENERATED("AutoGenerated"),
    CLAIM_DERIVED("ClaimDerived"),
    USER_DEFINED("UserDefined");

    private final String wireName;

    SlugSource(String wireName) { this.wireName = wireName; }

    @JsonValue
    public String getWireName() { return wireName; }
}
